enum ControlName {
    FOOT_PEDAL = 'Foot_Pedal',
    UP_ARROW = 'Up_Arrow',
    DOWN_ARROW = 'Down_Arrow',
    LEFT_ARROW = 'Left_Arrow',
    RIGHT_ARROW = 'Right_Arrow',
    SHIFT_BUTTON = 'Shift_Button',
    SELECT_BUTTON = 'Select_Button',
    DELETE_BUTTON = 'Delete_Button',
    DUPLICATE_BUTTON = 'Duplicate_Button',
    QUANTIZATION_BUTTON = 'Quantization_Button',
    ACCENT_BUTTON = 'Accent_Button',
    IN_BUTTON = 'In_Button',
    OUT_BUTTON = 'Out_Button',
    MASTER_SELECT_BUTTON = 'Master_Select_Button',
    OCTAVE_DOWN_BUTTON = 'Octave_Down_Button',
    OCTAVE_UP_BUTTON = 'Octave_Up_Button',
    REPEAT_BUTTON = 'Repeat_Button',
    GLOBAL_MUTE_BUTTON = 'Global_Mute_Button',
    GLOBAL_SOLO_BUTTON = 'Global_Solo_Button',
    TRACK_STOP_BUTTON = 'Track_Stop_Button',
    SCALE_PRESETS_BUTTON = 'Scale_Presets_Button',
    VOL_MIX_MODE_BUTTON = 'Vol_Mix_Mode_Button',
    DEVICE_MODE_BUTTON = 'Device_Mode_Button',
    CLIP_MODE_BUTTON = 'Clip_Mode_Button',
    BROWSE_MODE_BUTTON = 'Browse_Mode_Button',
    SINGLE_TRACK_MODE_BUTTON = 'Single_Track_Mode_Button',
    PAN_SEND_MODE_BUTTON = 'Pan_Send_Mode_Button',
    NODE_MODE_BUTTON = 'Note_Mode_Button',
    SESSION_MODE_BUTTON = 'Session_Mode_Button',
    // 'Play_Button',
    NEW_BUTTON = 'New_Button',
    AUTOMATION_BUTTON = 'Automation_Button',
    TAP_TEMPO_BUTTON = 'Tap_Tempo_Button',
    METRONOME_BUTTON = 'Metronome_Button',
    FIXED_LENGTH_BUTTON = 'Fixed_Length_Button',
    // 'Record_Button',
    UNDO_BUTTON = 'Undo_Button',
    CREATE_DEVICE_BUTTON = 'Create_Device_Button',
    CREATE_TRACK_BUTTON = 'Create_Track_Button',
    DOUBLE_BUTTON = 'Double_Button',
    USER_BUTTON = 'User_Button',
    TRACK_SELECT_BUTTON_0 = 'Track_Select_Button0',
    TRACK_SELECT_BUTTON_1 = 'Track_Select_Button1',
    TRACK_SELECT_BUTTON_2 = 'Track_Select_Button2',
    TRACK_SELECT_BUTTON_3 = 'Track_Select_Button3',
    TRACK_SELECT_BUTTON_4 = 'Track_Select_Button4',
    TRACK_SELECT_BUTTON_5 = 'Track_Select_Button5',
    TRACK_SELECT_BUTTON_6 = 'Track_Select_Button6',
    TRACK_SELECT_BUTTON_7 = 'Track_Select_Button7',
    TRACK_SELECT_BUTTONS = 'Track_Select_Buttons',
    TRACK_STATE_BUTTON_0 = 'Track_State_Button0',
    TRACK_STATE_BUTTON_1 = 'Track_State_Button1',
    TRACK_STATE_BUTTON_2 = 'Track_State_Button2',
    TRACK_STATE_BUTTON_3 = 'Track_State_Button3',
    TRACK_STATE_BUTTON_4 = 'Track_State_Button4',
    TRACK_STATE_BUTTON_5 = 'Track_State_Button5',
    TRACK_STATE_BUTTON_6 = 'Track_State_Button6',
    TRACK_STATE_BUTTON_7 = 'Track_State_Button7',
    TRACK_STATE_BUTTONS = 'Track_State_Buttons',
    SCENE_LAUNCH_BUTTON_0 = 'Scene_Launch_Button0',
    SCENE_LAUNCH_BUTTON_1 = 'Scene_Launch_Button1',
    SCENE_LAUNCH_BUTTON_2 = 'Scene_Launch_Button2',
    SCENE_LAUNCH_BUTTON_3 = 'Scene_Launch_Button3',
    SCENE_LAUNCH_BUTTON_4 = 'Scene_Launch_Button4',
    SCENE_LAUNCH_BUTTON_5 = 'Scene_Launch_Button5',
    SCENE_LAUNCH_BUTTON_6 = 'Scene_Launch_Button6',
    SCENE_LAUNCH_BUTTON_7 = 'Scene_Launch_Button7',
    SCENE_LAUNCH_BUTTONS = 'Scene_Launch_Buttons',
    // '0_Clip_0_Button',
    // '1_Clip_0_Button',
    // '2_Clip_0_Button',
    // '3_Clip_0_Button',
    // '4_Clip_0_Button',
    // '5_Clip_0_Button',
    // '6_Clip_0_Button',
    // '7_Clip_0_Button',
    // '0_Clip_1_Button',
    // '1_Clip_1_Button',
    // '2_Clip_1_Button',
    // '3_Clip_1_Button',
    // '4_Clip_1_Button',
    // '5_Clip_1_Button',
    // '6_Clip_1_Button',
    // '7_Clip_1_Button',
    // '0_Clip_2_Button',
    // '1_Clip_2_Button',
    // '2_Clip_2_Button',
    // '3_Clip_2_Button',
    // '4_Clip_2_Button',
    // '5_Clip_2_Button',
    // '6_Clip_2_Button',
    // '7_Clip_2_Button',
    // '0_Clip_3_Button',
    // '1_Clip_3_Button',
    // '2_Clip_3_Button',
    // '3_Clip_3_Button',
    // '4_Clip_3_Button',
    // '5_Clip_3_Button',
    // '6_Clip_3_Button',
    // '7_Clip_3_Button',
    // '0_Clip_4_Button',
    // '1_Clip_4_Button',
    // '2_Clip_4_Button',
    // '3_Clip_4_Button',
    // '4_Clip_4_Button',
    // '5_Clip_4_Button',
    // '6_Clip_4_Button',
    // '7_Clip_4_Button',
    // '0_Clip_5_Button',
    // '1_Clip_5_Button',
    // '2_Clip_5_Button',
    // '3_Clip_5_Button',
    // '4_Clip_5_Button',
    // '5_Clip_5_Button',
    // '6_Clip_5_Button',
    // '7_Clip_5_Button',
    // '0_Clip_6_Button',
    // '1_Clip_6_Button',
    // '2_Clip_6_Button',
    // '3_Clip_6_Button',
    // '4_Clip_6_Button',
    // '5_Clip_6_Button',
    // '6_Clip_6_Button',
    // '7_Clip_6_Button',
    // '0_Clip_7_Button',
    // '1_Clip_7_Button',
    // '2_Clip_7_Button',
    // '3_Clip_7_Button',
    // '4_Clip_7_Button',
    // '5_Clip_7_Button',
    // '6_Clip_7_Button',
    // '7_Clip_7_Button',
    // 'Button_Matrix',
    // 'Double_Press_Matrix',
    SINGLE_PRESS_EVENT_MATRIX = 'Single_Press_Event_Matrix',
    DOUBLE_PRESS_EVENT_MATRIX = 'Double_Press_Event_Matrix',
    TEMPO_CONTROL_TAP = 'Tempo_Control_Tap',
    TEMPO_CONTROL = 'Tempo_Control',
    SWING_CONTROL_TAP = 'Swing_Control_Tap',
    SWING_CONTROL = 'Swing_Control',
    MASTER_VOLUME_TAP = 'Master_Volume_Tap',
    MASTER_VOLUME_CONTROL = 'Master_Volume_Control',
    TRACK_CONTROL_TOUCH_0 = 'Track_Control_Touch_0',
    TRACK_CONTROL_TOUCH_1 = 'Track_Control_Touch_1',
    TRACK_CONTROL_TOUCH_2 = 'Track_Control_Touch_2',
    TRACK_CONTROL_TOUCH_3 = 'Track_Control_Touch_3',
    TRACK_CONTROL_TOUCH_4 = 'Track_Control_Touch_4',
    TRACK_CONTROL_TOUCH_5 = 'Track_Control_Touch_5',
    TRACK_CONTROL_TOUCH_6 = 'Track_Control_Touch_6',
    TRACK_CONTROL_TOUCH_7 = 'Track_Control_Touch_7',
    TRACK_CONTROL_TOUCHES = 'Track_Control_Touches',
    TRACK_CONTROL_0 = 'Track_Control_0',
    TRACK_CONTROL_1 = 'Track_Control_1',
    TRACK_CONTROL_2 = 'Track_Control_2',
    TRACK_CONTROL_3 = 'Track_Control_3',
    TRACK_CONTROL_4 = 'Track_Control_4',
    TRACK_CONTROL_5 = 'Track_Control_5',
    TRACK_CONTROL_6 = 'Track_Control_6',
    TRACK_CONTROL_7 = 'Track_Control_7',
    TRACK_CONTROLS = 'Track_Controls',
    DISPLAY_LINE_0 = 'Display_Line_0',
    DISPLAY_LINE_1 = 'Display_Line_1',
    DISPLAY_LINE_2 = 'Display_Line_2',
    DISPLAY_LINE_3 = 'Display_Line_3',
    SHIFTED_BUTTON_MATRIX = 'Shifted_Button_Matrix',
    TOUCH_STRIP_TAP = 'Touch_Strip_Tap',
    TOUCH_STRIP_CONTROL = 'Touch_Strip_Control',
}

export default ControlName
